spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/quarkus-based-application/configs
          clone-on-start: true
          skip-ssl-validation: true

server:
  port: 8888
